## Obsah rozhovoru (T) – témata a jejich odpovědi (jen data, logika je v `Dialog`).
## Každé téma = jeden záměr (intent) stejného jména. Pole tématu:
##   words   – klíčová slova (bez diakritiky, začátek slova; u nových záměrů – staré jsou v `Dialog.WORDS`)
##   lines   – obecné odpovědi (váha 1)
##   trait   – povaha postavy → odpovědi navíc (váha 2)
##   cond    – podmínka (viz `Dialog._conds`: raining, winter, night, recent_fish, carry_game, friend, …) → odpovědi (váha 4, jen když platí)
##   season  – roční období (jaro / léto / podzim / zima) → odpovědi (váha 3)
##   why     – odpovědi na navazující „a proč?“
##   ask     – klíče otázek, které postava sama položí zpět (`DialogData.ASKBACK`)
##   mood    – změna nálady za toto téma (0 = žádná)
##   social  – true: opakování téma neomezuje (pozdrav, poděkování…)
## Zástupné znaky v textu: {voc} oslovení, {first} / {name} / {job} / {hobby} postava, {g:rád|ráda} mužský|ženský tvar,
## {pub} hospoda, {shop} obchod, {temp} teplota, {season} období, {other} jiná postava (jméno), {other_job} její povolání.
## Jména a místa jsou smyšlená (viz README → Právní zásady obsahu).
class_name DialogThemes
extends RefCounted

const THEMES := {
	"weather": {
		"lines": ["Počasí se dneska chová, jak chce. Jako vždycky.", "Podle mě se to zase obrátí, počasí je vrtkavé.",
			"Teplota {temp}, tak nějak to na vsi bývá.", "Nebe se mračí, nebo se směje – podle toho, jak se vyspím.",
			"Po vsi se o počasí mluví víc než o politice. A to je co říct."],
		"trait": {"moudry": ["Stará pranostika praví: když se kočka drbe za uchem, bude pršet. Ale mně to říkají klouby.", "Za mých let se dalo počasí poznat podle vlaštovek. Dnes koukám na telefon jako ostatní."],
			"mlady": ["Koukám do aplikace a stejně to pokaždé vyjde jinak.", "Hlavně ať je signál, počasí mi je jedno."],
			"bruclavy": ["Počasí je vždycky špatné – buď moc sucho, nebo moc mokro.", "Kloub mě bolí, takže bude pršet. Nebo ne. Co já vím."],
			"veselak": ["Na pivo je dobře vždycky, počasí hraje druhé housle!", "Když prší, je to výmluva zůstat v hospodě."]},
		"cond": {"raining": ["Prší. Aspoň nemusím zalévat.", "Při dešti se dobře sedí doma u okna, ale ven to člověka stejně táhne.", "Z takového deště budou houby, to vám říkám."],
			"snowing": ["Sněží! Na silnici opatrně, ať neskončíš v příkopě.", "Sníh je krásný, dokud se nemusí odhazovat.", "Tohle je první pořádná nadílka, co?"],
			"hot": ["Horko jak v peci, to se nedá vydržet.", "V tomhle vedru nejdřív do stínu, pak teprve na práci.", "Kdo je chytrý, pije vodu a chodí jen ráno a večer."],
			"cold": ["Je to pořádná kosa, obleč se.", "Dneska mrzne, že i myšky sedí v díře.", "V tomhle počasí se nejlíp topí v kamnech."],
			"fog": ["Mlha, že není vidět na krok. Na silnici pomalu!", "V mlze se ráno lehce zabloudí, dej pozor na cesty kolem lesa."],
			"windy": ["Dneska fouká, až se střechy zvedají.", "Vítr je dnes silný – pod stromy radši nestůj, větve padají."],
			"snowcover": ["Sníh ještě leží, na cestách bude kluzko.", "Ve sněhu je vidět každá stopa, i ta liščí."],
			"sunny": ["Dneska je krásně, to se pracuje samo.", "Sluníčko svítí, to je radost vylézt z baráku."],
			"night": ["V noci se počasí hodnotí špatně, je tma.", "Hvězd je dneska vidět, je jasno."]},
		"season": {"jaro": ["Na jaře je to jako na houpačce – ráno sníh, v poledne slunce.", "Jaro je nevyzpytatelné, dnes teplo, zítra přízemní mráz."],
			"léto": ["V létě jsou nejhezčí bouřky, ale kdo je tahá z pole, ten to cení jinak.", "Léto nám letos dalo zabrat, ať už suchem, nebo lijáky."],
			"podzim": ["Na podzim to je jen mlha a déšť, ale taky hřiby.", "Podzim je na vsi nejhezčí, dokud nezačnou plískanice."],
			"zima": ["V zimě je tma brzo a zima dlouho.", "Zima se letos předvádí."]},
		"why": ["Počasí je prostě počasí, {voc}.", "To neví ani předpověď, natož já."],
		"ask": ["q_weather_walk"], "mood": 0.02,
	},
	"seasonwork": {
		"words": ["sezon", "co se ted dela", "co je ted k delani", "co ted delat", "jaka je ted prace", "co se ted sklizi", "co se ted seje",
			"co se ted sadi", "prace na jare", "prace v lete", "prace na podzim", "prace v zime", "co ted potrebuje", "co je ted potreba"],
		"lines": ["Každé roční období má svoji práci. Jen v zimě se dá aspoň vyspat.", "Na vsi se nikdy nenudíš – pořád je co dělat.",
			"Kdo nechce dělat, toho ves sežere. Tady se pořád něco kope, seká nebo zavařuje.", "Práce podle kalendáře, to je selský rozum.",
			"Jak se mění měsíce, tak se mění starosti. Člověk si zvykne.", "Nejdřív se seje, pak zalévá, pak sklízí, pak zavařuje a pak zase seje."],
		"trait": {"moudry": ["Za mých let se dělalo od svítání do setmění a nikdo nebrečel.", "Kdo neseje včas, nesklízí. To říkával otec."],
			"mlady": ["Brigáda v sadu, to je moje sezona. Jinak mě práce moc netáhne.", "Dřív jsem si myslel, že práce na vsi je nuda. Ona je to fuška."],
			"bruclavy": ["Práce je pořád dost, času málo, peněz taky.", "Sezona je, když člověk nestíhá nic."]},
		"season": {"jaro": ["Teď je čas sít a sázet – brambory, mrkev, salát. Až zmizí mrazíky.", "Na jaře se kope zahrada, seká první tráva a sází stromky.", "Jaro je práce na poli i na zahradě. Kdo zmešká duben, doplatí na to v září."],
			"léto": ["V létě se sklízí, zaléVá a sečou louky. A hlavně hlídej, ať nezapálíš trávu.", "Teď je žeň, seno a zavařování. Když pracuješ venku, pij hodně vody.", "Léto je na zálivku a sklizeň rajčat a dýní."],
			"podzim": ["Na podzim se sklízí ovoce, zavařuje, pálí slivovice a chystá dřevo na zimu.", "Teď je čas nasekat dříví a uklidit zahradu. Kdo to nechá na prosinec, ten zmrzne.", "Houby, jablka a brambory, to je podzim. Kdo si je sám vykope, má co jíst."],
			"zima": ["V zimě se topí, seká dřevo a opravuje nářadí. Ve sněhu se hlavně hodně sedí.", "V zimě je práce s dřívím, krmením zvěře a odklízením sněhu.", "Zimní práce? Nasekat a přiložit. A nezapomenout na zimní boty."]},
		"why": ["Protože příroda si poroučí, {voc}. Kdo jí vyhoví, má co jíst."],
		"ask": ["q_garden", "q_wood"],
	},
	"garden": {
		"words": ["zahrad", "zahon", "sazet", "sadit", "kopat", "plevel", "plet", "rajcat", "brambor", "zalev", "urod", "semen", "sklizen", "mrkev", "cibul", "salat", "okurk", "dyne", "kompost", "hnoj", "motyk", "lopat"],
		"lines": ["Zahrada je moje radost i trápení. Plevel roste rychleji než zelenina.", "Brambory a mrkev jsou základ. Z rajčat mám každý rok radost.",
			"Když ti zahrada nejde, zkus ji víc zalévat a míň radit.", "Zahrádka po práci, to je lepší než televize.",
			"Hlavně nesázej všechno naráz. Nejdřív jedna záhonka a uvidíš.", "Dobrá zahrada znamená dobrou zimu. Sklep plný, spíž taky.",
			"Kdo má zahradu, ten má i práci. Ale taky čerstvý salát přímo z hlíny."],
		"trait": {"drbna": ["Hromádková z rohu má letos rajčata jak pěsti, já tedy taky, jen o něco menší!", "Sousedka mi radí, jak mám zalévat. Pak jí to ukážu na svých jiřinách."],
			"moudry": ["Brambory se sázejí, když kvete trnka. Tak to říkala babička.", "Do půdy se musí dát srdce, pak ti to vrátí."],
			"mlady": ["Zahrada je pro mě fuška, ale babička to zvládá jedním prstem.", "Na záhonu mám salát. A jednu dýni, co je větší než moje hlava."],
			"veselak": ["Okurky na kvašák, rajčata na pivo, a hlavně něco na grilování!", "Zalévám po ránu. Dopoledne už se chodí zalít jinam."],
			"bruclavy": ["Slimáci mi sežrali salát. Příště je otrávím.", "Tohle loňské sucho mi zničilo půlku záhonu."]},
		"cond": {"raining": ["Dneska aspoň nemusím zalévat, to je na dešti to nejlepší.", "Déšť je pro zahrádku jako polévka pro nemocné."],
			"carry_seeds": ["Semínka nosíš v kapse? Sázej včas, ať ti nezplesniví.", "Semínka už máš, teď ještě záhon a konev."],
			"carry_veg": ["Z té zeleniny, co neseš, bude dobrá polévka. Zkus ji uvařit na ohni.", "Zelenina z vlastní zahrady, to je poklad. V Potravinách ji prý vykupují."],
			"recent_harvest": ["Slyšel{g:|a} jsem, že ses činil na zahradě. Sklizeň se povedla?", "Sklidit vlastní úrodu je největší odměna, co?"],
			"hot": ["V tomhle vedru zalévej brzo ráno nebo večer, ne na poledni.", "Rajčata v horku žízní, dej jim vody."]},
		"season": {"jaro": ["Na jaře se kope a sází. Brambory do půdy, mrkev, salát, cibule.", "Jaro je čas na záhony. Dávej pozor na mrazíky, rajčata nesázej moc brzo."],
			"léto": ["V létě se zalévá a sklízí. Hlavně nenech úrodu zkazit.", "V létě je na zahradě práce od rána: plít, zalévat, sklízet a hlavně se dívat, jestli něco nesežrali slimáci."],
			"podzim": ["Na podzim se sklízí brambory, cibule, dýně a zavařuje. Pak se musí zahrada uklidit.", "Podzimní zahrada voní po jablkách a zemi."],
			"zima": ["V zimě zahrada odpočívá a já s ní. Jen mám plánek na další rok.", "Zahrada spí pod sněhem, ale nářadí se musí připravit."]},
		"why": ["Protože zahrada chce pravidelnou péči, {voc}. Lenost se vymstí.", "Půda je živá, musí se ji krmit, zalévat a nesmí se jí dát moc."],
		"ask": ["q_garden"],
	},
	"animals": {
		"words": ["zvirat", "slepic", "kurnik", "kocic", "kocka", "kocour", "pes ", "psa ", "psi ", "pejsek", "kraval", "kozy", "kozu", "ovce", "ovci", "kralik", "kralic", "domaci zvir", "liska", "lisku", "prase", "praseta", "kun ", "vejce", "chov", "kohout"],
		"lines": ["Zvířata jsou jako děti – pořád chtějí jíst a nikdy nepoděkují.", "Kdo chová, musí krmit každý den. I když prší.",
			"Slepice ti dají vajíčka, králík maso a pes lásku. Kočka nic, ale to je kočka.", "Na vsi je zvíře skoro člen rodiny. A taky pracovní síla.",
			"Kdo nechová, nepochopí, jak je zvíře chytré. A jak umí být tvrdohlavé.", "Zvířata poznají dobrého člověka okamžitě. A ti špatní k nim ani nechodí."],
		"trait": {"pratelsky": ["Naši psi pozdraví každého. Jen poštáka ne.", "Sousedčina kočka mi chodí na návštěvu. Dávám jí mlíčko a říkám jí princezna."],
			"bruclavy": ["Zase mi liška vybrala kurník! Holota zlodějská.", "Slepice hloupé, kohout zlý, pes líný. Ale bez nich to nejde."],
			"moudry": ["Před válkou měl každý ve vsi krávu. Dneska je to hlavně pes a kočka.", "Zvíře nikdy nelže, to člověk umí jen on."],
			"plachy": ["Psa mám raději než lidi. Ten aspoň neřeční.", "Zvířata nemluví, to se mi líbí."],
			"mlady": ["Když budu mít vlastní byt, pořídím si kočku. Možná.", "Chov? Radši koukám na zvířata na videích."]},
		"cond": {"recent_hunt": ["Slyšel{g:|a} jsem, žes byl{g:|a} na lovu. Zvěř má ve vsi víc fanoušků než lovců.", "Na lovu? Doufám, že jsi to udělal{g:|a} po právu."],
			"night": ["V noci se slepice bojí každého zašustění. Liška to ví.", "V noci je venku i zvěř, dej pozor na silnici."],
			"winter": ["V zimě zvířata potřebují víc krmení a teplo. Seno a granule jsou poklad.", "V mrazu nechej zvířatům vodu, aby nezamrzla."]},
		"season": {"jaro": ["Na jaře se rodí mladá zvěř a kuřata. Je to radost, ale i starost.", "Jaro je čas na kuřata. Slepice sedí na vejcích a kohout se vytahuje."],
			"léto": ["V létě stačí zvířatům pastva a hlavně voda.", "Léto je na pastvu. Ale dávej pozor na klíšťata."],
			"podzim": ["Na podzim se zvířata dokrmují na zimu.", "Na podzim slepice línají a snáší míň vajec."],
			"zima": ["V zimě snáší slepice míň a musí se jim dát teplo.", "V zimě se zvířata musí víc krmit a chránit před mrazem."]},
		"why": ["Protože zvířata nemají hlas, {voc}, tak musíme za ně mluvit my."],
		"ask": ["q_pet"],
	},
	"fishing": {
		"words": ["ryb", "udic", "kapr", "rybnik", "pstruh", "navnad", "berou", "zizal", "podberak", "sumec", "candat", "stika", "lin ", "plotic", "okoun"],
		"lines": ["Rybařit se má ráno, nebo večer. Ve dne ryby spí.", "Trpělivost je základ. Kdo nevydrží sedět, ten ryby nechytí.", "Ryby neberou, když jsou moc slunce a moc hluk.",
			"U vody si člověk vyčistí hlavu, i když nic nechytí.", "Na rybníku se dobře sedí. Ryby jsou jen záminka.", "Dobrá návnada, dobrá ryba. Žížaly jsou klasika.", "Největší kapr vždycky utekl, to ví každý rybář."],
		"trait": {"plachy": ["U vody je klid. Lidi moc mluví.", "Když rybařím, nikdo se mě na nic neptá. To je krása."],
			"moudry": ["Před padesáti lety byly ryby až k pasu. Dneska jich je míň.", "Rybaření je filozofie. Sedíš a čekáš, až se něco stane."],
			"veselak": ["Ryba na talíři a pivo po boku, to je pohoda!", "Chytil jsem kapra, co vážil víc než tchyně. No, skoro."],
			"bruclavy": ["Dneska ryby neberou, protože je dobrý vítr. Nebo špatný.", "Rybařit se dá, jen nesmí být plno lidí."]},
		"cond": {"recent_fish": ["Slyšel{g:|a} jsem, že jsi něco chytil! Gratuluju. Co to bylo?", "Úlovek? No to je dobře. Příště přines ukázat."],
			"carry_fish": ["Ty neseš rybu? To je hezký kousek. Na pekáč nebo do udírny?", "Ta ryba na tebe vypadá velice pyšně."],
			"carry_rod": ["Máš udici! Tak na kapra na rybník, nebo do potoka?", "S udicí v ruce se dáš poznat. Chytají se hlavně kapři."],
			"raining": ["V dešti berou ryby dobře, ale ty sám zmokneš.", "Za deště je rybářům vlhko, ale rybám je to fuk."],
			"night": ["V noci na ryby? To chce nervy a lampu.", "Nočním rybářům se říká sumci. Nebo blázni."]},
		"season": {"jaro": ["Na jaře berou ryby hlavně červy a nejlíp po ránu.", "Jaro je začátek sezony. Kapři se probouzejí."],
			"léto": ["V létě se chytá brzo ráno a pozdě večer, v poledne je ryb jako šafránu.", "V létě se lovem ryb zchladíš jen u vody, ve stínu olší."],
			"podzim": ["Na podzim ryby přibírají na zimu, to jsou ty nejlepší kousky.", "Podzim je nejlepší čas na velké kapry."],
			"zima": ["V zimě se rybaří zřídka – pokud nezamrzne voda, berou ryby pomalu.", "V zimě je na rybníce led a klid."]},
		"why": ["Protože ryba je chytrá. Musí ti to dát najevo, že chce, abys ji chytil."],
		"ask": ["q_fish"],
	},
	"hunting": {
		"words": ["lov", "myslives", "srn", "divocak", "zajic", "posed", "puska", "pytlak", "zver", "kuse", "luk ", "naboj", "zbrojni", "strelb", "krmelec"],
		"lines": ["Lov je odpovědnost, ne zábava. Kdo střílí, musí vědět, proč.", "Jenom s dokladem a jen v době lovu. Ostatní je pytláctví.", "Myslivec se v lese pohybuje potichu a nestřílí na cokoliv.",
			"Zvěř patří lesu. My jsme jen hosté.", "Dobrá rána je taková, co zvíře nenechá trpět.", "V lese je klid a v klidu se nejlépe přemýšlí o zvěři."],
		"trait": {"bruclavy": ["Divočáci mi rozryli louku! A pytláci mi střílí srny. Ti jsou horší než zvěř.", "Myslivost? To je práce, nikdo nevidí, jak se v noci krmí."],
			"moudry": ["Za mých let se stříleli jen bažanti a zajíci. Dneska je jich míň.", "Kdo jednou zastřelil, ví, že to není hra."],
			"prisny": ["Lov bez povolení je trestný čin. Chápete to?", "Zbraně patří do rukou těch, kdo mají papíry."],
			"plachy": ["Do lesa chodím jen s dalekohledem. Ta zvěř je krásná.", "Střílet? Nikdy. Ale koukat ano."]},
		"cond": {"recent_hunt": ["Slyšel{g:|a} jsem, žes něco ulovil. Hlavně ať to bylo po právu.", "Lov je práce. A tys měl{g:|a} úspěch?"],
			"recent_poach": ["O tobě se povídá, že jsi lovil{g:|a} bez dokladů. To není dobré.", "Pytláctví se tady nenosí. Raději to neopakuj."],
			"carry_gun": ["Ty jdeš ozbrojen{g:ý|á}? Doufám, že máš papíry.", "Se zbraní po vsi chodit nemáš. V lese je to jiná."],
			"carry_game": ["Ta zvěřina na tebe vypadá, že je čerstvá. Máš doklad o původu?", "Pěkný kus! Jen nezapomeň na vyvržení."],
			"night": ["V noci se nestřílí. Kdo to dělá, ten je pytlák."]},
		"season": {"jaro": ["Na jaře se nestřílí, zvěř má mláďata.", "Jaro je čas krmelců a pozorování. Lov se nechává na později."],
			"léto": ["V létě se střílí jen vybraná zvěř a hlavně nikdy mláďata.", "V létě je práce hlavně s ohradami a posedy."],
			"podzim": ["Na podzim je hlavní sezona – srnci, divočáci a zajíci.", "Podzim je čas honů a posedů. Les je plný zvěře."],
			"zima": ["V zimě se krmí a hlídá. Zvěř hladoví, tak jí pomáháme.", "Zimní lov je těžký a tichý. Sníh prozradí každou stopu."]},
		"why": ["Protože zákon je zákon, {voc}, a les patří všem.", "Zvěř není neomezená, musí se s ní hospodařit."],
		"ask": ["q_hunt"],
	},
	"wood": {
		"words": ["drev", "polen", "sekera", "sekery", "sekeru", "pila ", "pilu", "pily", "motorovk", "kacet", "kaceni", "klest", "kamna", "krb", "topit", "topeni", "vetve", "vetvi", "pan ", "paren", "drevo"],
		"lines": ["Dřevo dvakrát zahřeje: jednou když ho nasekáš a pak když ho spálíš.", "Sekera a pořádné rukavice, to je základ. A hlavně hlava.", "Dřevo se suší aspoň rok. Mokré dřevo jen čadí.",
			"Kdo topí dřevem, ví, že zima se začíná připravovat v létě.", "Motorová pila je dar i prokletí. Bez ochrany nechoď ani k prknu.", "V lese se bez povolení nekácí, to je zákon. Na vlastní zahradě si dělej, co chceš."],
		"trait": {"prisny": ["Kácet bez povolení je přestupek. Víte, že za to hrozí pokuta?", "Motorová pila bez ochranných kalhot je hazard."],
			"moudry": ["Dřevo je poklad. Kdo má dřevo, má teplo.", "Sekat se má pomalu a rovně. Sílu si nech na nošení."],
			"bruclavy": ["Dneska nikdo neumí pořádně naštípat polínko.", "Sousedi mi kradou klest. Nechám si k tomu pořídit psa."],
			"veselak": ["Nasekané dřevo dvakrát zahřeje: pak i třetí, když se u toho napiješ!", "Dřevo a pivo, to je mužská práce. A ženská taky."]},
		"cond": {"recent_tree": ["Slyšel{g:|a} jsem, že jsi porazil strom. Doufám, že na svém.", "Pokácený strom? Hlavně ať nespadl na cizí plot."],
			"carry_axe": ["Máš sekeru! Je to dobrý nástroj, jen pozor na nohy.", "S tou sekerou opatrně, ať nepřijdeš o palec."],
			"carry_wood": ["Dřevo nosíš? To bude pěkný oheň.", "Polena ti přijdou vhod na zimu. Nebo se dají prodat do Pálenice."],
			"winter": ["V zimě je dřevo nejvíc, co si člověk může přát.", "V mrazu je klestí k ohni nejdražší."],
			"raining": ["Mokré dřevo nehoří, tak ho nech v suchu."]},
		"season": {"jaro": ["Na jaře se dřevo dosouší a chystají se nové špalky.", "Jaro je čas uklidit dřevník a nachystat dřevo na příští rok."],
			"léto": ["V létě se dělá dřevo na zimu. Kdo ho nasekal, má klid.", "V létě je nejlepší čas na štípání a sušení."],
			"podzim": ["Na podzim se dřevo naváží a uloží. Nejpozději do první zimy.", "Podzim je sezona pily a sekery."],
			"zima": ["V zimě se topí a doplňuje. Suché dřevo je zlato.", "Zimní dřevo musí být suché. Mokré jen čadí."]},
		"why": ["Protože les není skladiště zdarma, {voc}. Každý strom je něčí."],
		"ask": ["q_wood"],
	},
	"fire": {
		"words": ["ohen", "ohn", "ohniste", "zapalit", "zapalk", "sirk", "zapalovac", "pozar", "hasit", "grilov", "vatra", "kourit", "zar ", "uhli", "opekat", "opekan", "burt"],
		"lines": ["Oheň je dobrý sluha a zlý pán. Nikdy ho nenech bez dozoru.", "Při rozdělávání ohně potřebuješ suché větvičky a trpělivost.", "Oheň se rozdělává v kamenném kruhu, ne na suché louce.",
			"U ohně se nejlíp povídá. A jídlo z něj chutná nejvíc.", "Oheň v lese nikdy. Jedna jiskra a po vsi jsou všichni v pozoru.", "Kdo jednou viděl hořet les, už si se sirkami nehraje."],
		"trait": {"pratelsky": ["Opékání buřtů je radost pro celou rodinu. Jen si je neupal.", "U ohně se přátelé najdou a problémy spálí."],
			"prisny": ["Pálit v lese nebo u lesa je přestupek. Nebudu to opakovat.", "Oheň musí mít dozor. Kdo odejde, je zodpovědný."],
			"moudry": ["Oheň je stará věc. Naši předkové u něj žili.", "U vatry se vyprávělo a mládež to poslouchala."],
			"mlady": ["Buřty na ohni, to je top. Jen bez dozoru ne.", "Zapálit oheň není problém. Uhasit ho je ten problém."]},
		"cond": {"raining": ["V dešti oheň nechytá. Potřebuješ suché roznětky.", "Déšť oheň zhasíná, takže si dej pozor na vlhké dřevo."],
			"windy": ["V takovém větru oheň nerozděláváš, jiskry by lítaly po celé louce.", "Vítr oheň rozdmýchává. Buď hodně opatrný."],
			"summer": ["V létě je sucho a stačí jiskra, a hoří tráva. Buď opatrný.", "V létě oheň jen v ohništi a s vodou po ruce."],
			"recent_fire": ["Slyšel{g:|a} jsem, že jsi rozdělal oheň. Doufám, že jsi ho pořádně uhasil.", "Oheň? Hlavně ať po sobě nezůstane žhavé dřevo."],
			"carry_wood": ["S tím dřívím si můžeš rozdělat pěkný oheň, ale ne v lese."]},
		"season": {"zima": ["V zimě je oheň nejlepší kamarád, ale nejdřív je třeba nasbírat suché dřevo.", "V zimě se oheň hodí k ohřátí i k vyschnutí."],
			"léto": ["V létě je největší riziko požáru trávy. Hlavně nenech oheň bez dohledu.", "V létě u ohně sedíme jen večer."]},
		"why": ["Protože oheň nikdy neodpouští chyby, {voc}."],
		"ask": ["q_fire"],
	},
	"cars": {
		"words": ["auto", "autak", "autem", "autu", "bazar", "kara", "karu", "vuz ", "pneu", "servis", "benzin", "nafta", "nafty", "stk", "tachomet", "kombi", "motorov", "spz", "ridic", "motork", "kolo ", "kole", "cyklo", "dodavk"],
		"lines": ["Auto musí mít duši, ne jen displej. Nové vozy jsou samá elektronika.", "Bazar je loterie. Jednou koupíš poklad, podruhé trable.", "Na vsi se bez auta nedá žít, ale s ním se musí dávat pozor na díry.",
			"Staré auto je jako starý kamarád: občas zlobí, ale zná všechny silnice.", "Nejdřív pneumatiky a brzdy, pak teprve lak. Tak to říkal dědeček.", "Kdo si auto nedrží, ten ho nemá. Kdo ho drží, zaplatí servis."],
		"trait": {"mlady": ["Jednou si koupím pořádnou káru, uvidíte. Zatím šetřím.", "Nejlepší auto je to, co jede. Nejhorší to, co stojí v servisu."],
			"bruclavy": ["Silnice jsou samá díra. Každý týden jiná.", "Dneska se auto nedá opravit, všechno je v počítači."],
			"prisny": ["Řidič musí znát předpisy a mít papíry v pořádku.", "Rychlost zabíjí. Dodržujte ji."],
			"veselak": ["Auto je dobrá věc, ale pivo je lepší. Nikdy ne za volantem!", "Když řídím, jsem dobrý. A když ne, jdu pěšky."],
			"moudry": ["Za mých let jsme měli koně a povoz. Ten nikdy nezlobil a nepotřeboval benzín.", "Auto je pohodlí, ale kůň je přítel."]},
		"cond": {"in_car": ["Ty jsi v autě? No, ať ti to jede! A dávej pozor na srny.", "V autě jsi pán, ale silnice je všech."],
			"drunk": ["Ty a auto? V tomhle stavu ne. Jdi pěšky.", "S alkoholem za volant nikdy. To je základní pravidlo."],
			"recent_crash": ["Slyšel{g:|a} jsem, že ses s autem nepotkal dobře. Jsi v pořádku?", "Naboural jsi? Doufám, že nikomu nic není."],
			"winter": ["V zimě zimní pneumatiky, jinak skončíš v příkopě.", "V zimě se auto musí rozehřát a neutíkat."],
			"raining": ["V dešti nedávej plyn naplno, silnice kloužou.", "Za deště do zatáček pomalu. Brzdná dráha roste."]},
		"season": {"zima": ["V zimě dej na zimní gumy a nech si pomalu rozjet motor.", "Kluzká silnice v zimě, to je jízda."],
			"podzim": ["Na podzim je na silnici listí a mlha. Dej pozor na zvěř.", "Podzim je sezona srážek se zvěří."]},
		"why": ["Protože to tak chodí, {voc}. Auto potřebuje péči, jako každý."],
		"ask": ["q_car"],
	},
	"pub": {
		"words": ["stamgast", "v hospode", "hostinsk", "vycep", "zaviracka", "zavirac", "pivnic", "hospodsk", "co se deje v hospode", "v hospode je", "u hriste", "jak je v hospode"],
		"lines": ["V {pub} se sejde půl vsi. Kdo chce něco vědět, sedne si k výčepu.", "Hostinský ví všechno o všech. A nikomu nic neřekne. To je řemeslo.",
			"V hospodě je pravda. A taky pivo. To první je vzácnější.", "Ve čtvrtek je klid, v pátek je tam plno, v sobotu je tam hlučno.",
			"Hospoda je ve vsi srdce. Bez hospody je ves jen hromada domů.", "Dobrá hospoda poznáš podle toho, že se v ní dá hádat, a nikdo si to nebere osobně."],
		"trait": {"veselak": ["V hospodě je vždycky veselo. Kdo nepřijde, neví, o co přichází!", "Hostinský točí, já jen sedím. To je dělba práce."],
			"prisny": ["V hospodě chodím jen na oběd. Večer tam bývá hluk.", "Hospodu nemám. A nikomu ji nedoporučuji."],
			"bruclavy": ["V hospodě je to samý křik a cigaretový kouř. Ale pivo tam mají dobré.", "Dřív tam bývalo líp. Dneska tam chodí jen mladí."],
			"moudry": ["V hospodě se hraje karty a povídá. Mladí tam chodí jen s telefonem.", "Hospoda je škola života."]},
		"cond": {"night": ["V noci už to v hospodě končí. Nebo začíná, podle toho.", "V noci je hospoda zavřená, pokud není pátek."],
			"weekend": ["O víkendu bývá v hospodě plno. Kdo chce sedět, musí přijít brzy.", "V sobotu večer se v hospodě zpívá."],
			"event_hody": ["Na hodech je v hospodě živo, to tam nenajdeš místo k stání.", "Na hodech tancuje i ten, kdo nikdy netančil."],
			"drunk": ["Ty už jsi v hospodě byl, poznám to z dálky.", "Ty vypadáš, že hospodu navštěvuješ často."]},
		"season": {"zima": ["V zimě hospoda hřeje a zahrádka je prázdná.", "V zimě je hospoda druhý domov. Aspoň teplý."],
			"léto": ["V létě se sedí na zahrádce a pije studené pivo.", "V létě je na zahrádce nejlíp."]},
		"why": ["Protože lidi se chtějí scházet, {voc}. A pivo je dobrá záminka."],
		"ask": ["q_beer"],
	},
	"beer": {
		"words": ["jake pivo", "dobre pivo", "ktere pivo", "oblibene pivo", "pivo chutna", "nejlepsi pivo", "desitk", "dvanactk", "lezak", "rezany", "pivni", "pivo je", "na pivo", "pivovar", "tocene", "cepovane", "lahvove", "ctyrka"],
		"lines": ["Dvanáctka je klasika. Desítka k obědu, dvanáctka na večer.", "Pivo musí mít pořádnou pěnu. Kdo nalévá bez čepice, ten neumí.", "Pivo je tekutý chleba. A chleba je základ.",
			"Pivo se nalévá pomalu. Kdo spěchá, má víc pěny než piva.", "V {pub} točí čerstvé. Ve flaškách z obchodu je to už jiné.", "Jedno pivo nikomu neublíží. Druhé taky ne. Třetí přestává počítat."],
		"trait": {"veselak": ["Pivo je mé hobby. A taky moje povolání, když se zeptáš mé ženy.", "Pivo je dobré, pivo je zdravé. Aspoň to tvrdím, když u něj sedím!"],
			"prisny": ["Pivo? Nepiju. Zdraví je důležitější.", "Alkohol nemám rád. Zvlášť ne za volantem."],
			"moudry": ["Pivo jsme pili už za mladu. Bylo chudší, ale chutnalo líp.", "Pivo patří k obědu, jak pravil můj děd."],
			"bruclavy": ["Dneska pivo není co bývalo. Je vodnaté.", "Pivo dobré je, jen cena šla nahoru."]},
		"cond": {"carry_beer": ["Ty neseš pivo? To je dobrý základ pro večer.", "Pivo v ruce a pohoda v duši, to je on!"],
			"drunk": ["Tobě už pivo nenalévat.", "Ty jsi už asi na pivo měl{g:|a} dost."],
			"hot": ["V tomhle vedru je studené pivo záchrana.", "Za horka pivo chutná nejlíp, ale hlavně hodně vody!"],
			"weekend": ["O víkendu se pivo točí nejvíc.", "V sobotu je zlatá hodinka u výčepu."]},
		"season": {"léto": ["V létě jde pivo na odbyt. Zahrádka je plná.", "V létě se pije studené a s citrónem, pokud někdo chce."],
			"zima": ["V zimě se pije pivo s rumem, tedy někteří.", "V zimě je pivo teplé, protože se sedí u kamen."]},
		"why": ["Protože pivo je dobré, {voc}. Nepotřebuje důvod."],
		"ask": ["q_beer"],
	},
	"football": {
		"words": ["fotbal", "zapas", "hriste", "liga", "gol", "trener", "fandit", "brank", "hrac", "tym ", "hraji"],
		"lines": ["V neděli je zápas, přijď fandit! Hřiště je za obcí.", "Náš útok je slabý, ale srdce máme velké.", "Fotbal je jediná věc, o které se dá hádat celé odpoledne a ještě večer.",
			"Kluci trénují v úterý a ve čtvrtek. Kdo přijde, má místo.", "Fotbal je pro vesnici jako knihovna pro město: všichni se tam potkají.", "Gól se nepočítá, dokud ho nezapíšeme do hospodské tabule."],
		"trait": {"veselak": ["Fotbal a pivo, to je základ. Po zápase se to hodnotí v hospodě!", "Trénuju, pijeme, hrajeme. Přesně v tomhle pořadí."],
			"prisny": ["Fotbal je fajn, ale nesmí to být výmluva pro hlučnost.", "Hřiště je v pořádku, ale chtělo by víc úklidu."],
			"mlady": ["Fotbal je top. Kopu každou neděli, když není kocovina.", "Dneska hraju hlavně na konzoli, ale ve skutečnosti taky!"],
			"moudry": ["Kdysi byl fotbal jiný. Míč těžký a boty hrozné.", "Fotbal je dobrý pro mládež, drží ji od lumpáren."]},
		"cond": {"weekend": ["Zápas je dneska nebo zítra, pojď se podívat!", "O víkendu se hraje, přijď fandit."],
			"event_hody": ["O hodech se hraje zápas svobodní proti ženatým. To musíš vidět!"],
			"winter": ["V zimě se netrénuje, hřiště spí pod sněhem.", "V zimě se hraje jen na papíře a v hospodě."],
			"raining": ["V dešti se hraje taky, jen blátivěji.", "Pršelo, takže hřiště je bahno. Kluci budou jak prasata."]},
		"season": {"jaro": ["Na jaře začíná sezona, to je radost.", "Jaro je čas na první zápasy."], "podzim": ["Na podzim se dohrává sezona a kluci mají blátivé boty.", "Podzim je na hřišti bahno, ale hra jde dál."]},
		"why": ["Protože fotbal je náš život, {voc}. Nepotřebuje důvod."],
		"ask": ["q_fotbal"],
	},
	"firefighters": {
		"words": ["hasic", "hasici", "sbor", "stricka", "soutez", "zasah", "sirena", "dobrovoln", "pozarni", "cisterna", "hadice"],
		"lines": ["Hasiči jsou základ vsi. Kdo hoří, koho zachrání? Oni.", "Soutěž je v červnu, to je sláva! Stříkačky, hadice a celá ves fandí.", "Sbor dobrovolných hasičů drží ves pohromadě. Bez nich by nebylo ani posvícení.",
			"Sirénu slyšíš jen jednou za čas, ale když zazní, všichni běží.", "Hasičská zbrojnice je největší budova ve vsi, co nemá kostelní věž.", "Hasič musí mít silná záda a klidnou hlavu."],
		"trait": {"pratelsky": ["U hasičů jsem byl čtyřicet let. Soutěže, to byla sláva!", "Hasiči mají svůj bál. Pojď, bude veselo."],
			"prisny": ["Hasiči mají respekt. Nikdy jim nepřekáž.", "Požární bezpečnost je vážná věc, ne legrace."],
			"veselak": ["Hasiči mají nejlepší zábavu! A taky hadici, ale to je vedlejší.", "Na hasičskou zábavu přijdu vždycky, hlavně kvůli pivu."],
			"moudry": ["Za mých let se chodilo hasit s vědry a bylo to těžší.", "Hasiči jsou největší hrdinové, co nikdy nikdo nevidí."]},
		"cond": {"recent_fire": ["Slyšel{g:|a} jsem, že jsi dělal{g:|a} oheň. Hasiči jsou rádi, když je to bezpečně.", "Oheň musí mít dozor. Hasiči to vědí nejlíp."],
			"summer": ["V létě je sucho a hasiči mají práci s travními požáry.", "V létě je hasičům nejhůř, hoří tráva."],
			"event_carodejnice": ["Na čarodějnice hasiči hlídají oheň. A taky pijí."]},
		"season": {"léto": ["V létě bývají soutěže a zábavy, to je hasičská sezona.", "V létě se hasiči potí, buď u ohně, nebo na soutěži."], "zima": ["V zimě hasiči opravují techniku a chystají bál.", "Zimní bál hasičů je událost roku."]},
		"why": ["Protože bez dobrovolných lidí by ves shořela, {voc}."],
		"ask": ["q_fire"],
	},
	"politics": {
		"words": ["starost", "zastupitel", "volby", "politik", "obecni zastupitelstvo", "vyhlas", "rozpocet", "oprava cest", "oprava silnic", "kanalizac", "obecni rozhlas", "rozhlas", "zasedani", "obec rozhodla", "predseda", "vlada"],
		"lines": ["Politika? Ta mě už nebaví. Ale radu dám.", "Starosta má nejtěžší práci ve vsi. Musí vyhovět všem a nikomu se to nepodaří.", "Na zastupitelstvu se hádají hlavně o silnice a lavičky.",
			"Obec má málo peněz a hodně nápadů. To je běžné.", "Všichni nadávají na starostu, ale nikdo nechce být na jeho místě.", "Volby jsou jednou za čas, stížnosti pořád."],
		"trait": {"prisny": ["Pořádek v obci je povinnost každého. Začíná u plotu a končí u starosty.", "Obecní vyhlášky se mají dodržovat, ne obcházet."],
			"moudry": ["Starostové přicházejí a odcházejí. Ves zůstává.", "Za mých let se politika dělala v hospodě. A nebylo to horší."],
			"bruclavy": ["Silnice samá díra a starosta samé sliby.", "Vždycky se něco opraví jen před volbami."],
			"drbna": ["Prý se na úřadě bude něco dít. Víš, co se povídá o rozpočtu?", "Starosta prý jednal s jedním pánem z města. A nikdo neví, o čem."]},
		"cond": {"event_masopust": ["Na masopust je starosta vždycky v masce. Nepoznáš ho."], "weekday": ["Na úřadě je otevřeno od sedmi do pěti. Starosta bývá dopoledne.", "Kdo chce něco vyřídit, ať jde na úřad ráno."],
			"respected": ["O tobě se mluví dobře i na úřadě. To se cení.", "Starosta o tobě prý dobře mluví."], "disliked": ["Na úřadě o tobě prý něco vědí. Nic dobrého.", "Starosta o tobě už slyšel, radši nezlob."],
			"recent_offense": ["Na úřadě se prý mluvilo o tvém přestupku. Dej si pozor."]},
		"season": {"podzim": ["Na podzim se rozhoduje o rozpočtu a zimní údržbě.", "Podzim je na úřadě čas plánování."], "zima": ["V zimě se řeší hlavně odhrnování sněhu a posyp.", "V zimě starosta nemá rád sníh. Všichni volají, že neodhrnuto."]},
		"why": ["Protože peněz je málo a přání hodně, {voc}."],
		"ask": ["q_politics"],
	},
	"neighbors": {
		"words": ["soused", "sousedi", "kdo bydli", "kdo tu bydli", "kdo je kdo", "obyvatel", "lide ve vsi", "kdo tu je", "ve vsi bydli", "kdo zije", "znas nejake lidi", "kdo je tu"],
		"lines": ["Ve vsi se všichni znají. To je dobře i špatně.", "Sousedé jsou jako počasí: nevybereš si je, ale musíš se s nimi bavit.", "Kdo tu žije dlouho, ví o všech všechno. Kdo nový, ten se to učí.",
			"Každý má svoje. Jen někdo víc nahlas.", "Zatím všichni držíme při sobě. Až na pár výjimek, samozřejmě.", "Ves je malá, ale příběhů je v ní víc než ve městě."],
		"trait": {"drbna": ["Můžu ti říct, kdo je kdo. Ale jen jestli to nepovíš dál.", "Co potřebuješ vědět? Já znám každého."],
			"prisny": ["Do cizích záležitostí se nepletu.", "Soused má dodržovat řád. Víc nevím."],
			"plachy": ["Lidi moc neznám. Jen pár.", "Raději zůstávám zticha."],
			"pratelsky": ["Máme tu dobré sousedy. Kdo potřebuje, ten dostane.", "Sousedi si pomáhají. Zvlášť při sklizni."]},
		"cond": {"stranger": ["Ty jsi tu novej, že? Brzo poznáš všechny.", "Tebe ještě neznám. Ale to se změní."], "friend": ["Ty už jsi skoro místní.", "Ty už tu patříš, to se nám líbí."]},
		"season": {"léto": ["V létě se sousedi víc potkávají na zahrádkách.", "V létě je ves živá, kdekdo sedí před domem."], "zima": ["V zimě se ves zavře. Lidi se vidí jen v hospodě a v obchodě.", "V zimě sousedi sedí doma, ale kouř z komínů je pozná."]},
		"why": ["Protože lidi jsou zvědaví, {voc}."],
		"ask": ["q_gossip"],
	},
	"family": {
		"words": ["rodin", "zena ", "manzel", "manzelk", "syn ", "synovi", "dcer", "bratr", "sestr", "rodic", "vnuk", "vnuc", "babicka", "dedecek", "tchyne", "tchan", "maminka", "tatinek", "deti mas", "mas deti", "mate deti", "dite"],
		"lines": ["Rodina je základ. Bez ní je člověk jako strom bez kořenů.", "Rodina se nevybírá, ale dobrá rodina je štěstí.", "Nedělní oběd u babičky, to je svatá věc.",
			"S rodinou to je jako s počasím: někdy hřeje, někdy bouří.", "Děti rostou rychle. Kdo nevěří, ať se podívá na fotky.", "Příbuzní se vidí nejčastěji na svatbách a pohřbech. A na Vánoce."],
		"trait": {"pratelsky": ["Rodina je pro mě všechno. Bez ní bych nebyla ani já.", "Mám rodinu, co si rozumí. To je dar."],
			"bruclavy": ["Rodina je hezká věc, dokud se nezačne dělit dědictví.", "Dneska nikdo nepřijde na návštěvu. Všichni mají telefon."],
			"moudry": ["Rodina je poklad. Kdo ji má, je bohatý.", "Za mých let se žilo pohromadě. Tři generace pod jednou střechou."],
			"plachy": ["Mám malou rodinu. Stačí mi to.", "Rodina je soukromá věc, nerad o ní mluvím."],
			"mlady": ["Rodina? Mám mámu a tátu. A ti mě vytáčí.", "S rodinou si rozumím, když nejsem doma."]},
		"cond": {"event_vanoce": ["O Vánocích se rodina schází. Mám už napečeno.", "Vánoce jsou jen s rodinou, to je svaté."], "weekend": ["O víkendu bývá rodinná návštěva. Dneska to tak vypadá i u nás.", "V neděli je rodinný oběd. Nikdy nechybíme."],
			"friend": ["Ty jsi skoro jako rodina. Přijď někdy na kafe.", "Kdybys potřeboval, dveře ti jsou otevřené, to ví celá rodina."]},
		"season": {"zima": ["V zimě se rodina schází u kamen a povídá.", "V zimě rodinné večery u kamen vynikají."], "léto": ["V létě se děti rozběhnou po vsi a rodiče je volají domů.", "V létě jezdí rodina k vodě."]},
		"why": ["Protože bez rodiny není kam se vracet, {voc}."],
		"ask": ["q_family"],
	},
	"childhood": {
		"words": ["detstvi", "jako kluk", "jako mlady", "kdyz jsi byl maly", "za mlada", "vzpominky", "vzpomink", "pamatujes", "pamatujete", "jak to tu bylo", "historie vsi", "dejiny", "kdysi", "driv", "drive", "pred lety", "za komunismu"],
		"lines": ["Dřív se chodilo pěšky do školy i za sněhu. A nikdo nebrečel.", "Když jsme byli malí, hráli jsme si na polích a v potoce. Nikdo nám nic neříkal.", "Za mých let jsme měli dřevěné hračky a fantazii.",
			"Kdysi tu byla větší spolupráce. Každý pomohl každému.", "Pamatuju si, jak se sklízelo v JZD, celá ves pohromadě.", "Dřív byla ves chudší, ale veselejší."],
		"trait": {"moudry": ["Pamatuju si ještě, kdy tu jezdily jen koňské povozy.", "Dřív se tady tancovalo na návsi každou neděli.", "Za mých mladých let se žilo hůř, ale lidi si víc pomáhali."],
			"bruclavy": ["Dřív bylo líp. Nebo jsem byl jen mladší.", "Za mě se nechodilo k doktorovi pro každou maličkost."],
			"drbna": ["Pamatuju, že to tu bývalo veselé. A drby byly ještě lepší.", "Znám tuhle ves od dětství, i její temné tajemství."],
			"mlady": ["Moje dětství byla ves a kolo. Bylo to fajn.", "Ve škole jsme měli tabuli a křídu, to už se nevidí."]},
		"cond": {"winter": ["V zimě jsme se sáňkovali z kopce za kostelem. Dodnes si pamatuji ten smích.", "Zimy bývaly dřív krutější. A my jsme byli odolnější."],
			"event_hody": ["Hody bývaly dřív větší. Kapela hrála do rána."], "friend": ["Tobě to povím: za mlada jsem byl{g:|a} hroznej rošťák.", "Ty jsi dobrý posluchač, nikomu takhle nevyprávím."]},
		"season": {"jaro": ["Na jaře jsme chodili na pomlázku. Dneska už se to nenosí tolik.", "Na jaře se chodilo na louky a sbíraly se kytky."], "podzim": ["Na podzim jsme pouštěli draky na strništi. To byly časy.", "Na podzim jsme pekli brambory v ohni."]},
		"why": ["Protože čas letí, {voc}, a vzpomínky zůstávají."],
		"ask": ["q_childhood"], "mood": 0.05,
	},
	"recipes": {
		"words": ["recept", "jak se vari", "jak uvarit", "jak upect", "jak se dela", "vareni", "varis", "pecem", "knedl", "svickov", "bramborak", "kulajda", "zelnack", "smazeny syr", "oblibene jidlo", "co dobreho", "kuchyn", "polevk", "pecene", "nadivk", "zavarovat", "zavarenin"],
		"lines": ["Nejlepší je bramborák. Brambory, česnek, majoránka a pořádný tuk.", "Kulajda je na podzim poklad: houby, brambory, kopr, smetana a vejce.", "Svíčková bez knedlíku není svíčková, ale jen omáčka.",
			"Polévka se vaří pomalu. Kdo spěchá, ten má jen horkou vodu.", "Bábovka musí být vláčná. A tajemství je v másle.", "Zelnačka zahřeje v zimě lépe než kamna.", "Dobré jídlo nepotřebuje moc věcí, jen dobré suroviny a čas."],
		"trait": {"pratelsky": ["V sobotu peču koláče – tvarohové, povidlové, makové. Přijď ochutnat!", "Dobré jídlo spraví náladu. Zkus to!"],
			"moudry": ["Babička vařila z ničeho a bylo to nejlepší jídlo na světě.", "Recept se nedědí v knize, ale v rukou."],
			"bruclavy": ["Dneska se nikdo neumí pořádně navařit. Všechno z pytlíku.", "Nejlepší jídlo je to, co uvaříš sám. Jen s ohněm si dej pozor."],
			"veselak": ["Guláš je základ! A k němu pivo, to je tradice.", "Nejlepší recept je: něco dobrého a hodně chuti!"]},
		"cond": {"carry_veg": ["Z té zeleniny by byla pěkná polévka. Přidej brambory a sůl.", "Zeleninu máš? Uvař si ji u ohně, nebo ji prodej v obchodě."], "carry_game": ["Ze zvěřiny je nejlepší pečeně s knedlíkem a brusinkami.", "Zvěřina se musí nechat pár dní uležet. Pak je měkká."],
			"carry_fish": ["Kapr se smaží v trojobalu a k němu bramborový salát. Nebo se dá upéct.", "Z rybí polévky je zlato, jen si dej pozor na kosti."], "winter": ["V zimě zelnačka a pečené brambory.", "V zimě se dobře vaří polévky a guláš."],
			"event_vanoce": ["O Vánocích se peče cukroví a smaží kapr, to je rodinná sláva."]},
		"season": {"jaro": ["Na jaře je dobrá kopřivová polévka a čerstvý salát.", "Na jaře se vaří lehká jídla: špenát, ředkvičky, mladá cibulka."], "léto": ["V létě jsou dobré rajčata a okurky, a hlavně ovoce.", "V létě se vaří lehce, nejlépe na ohni."],
			"podzim": ["Na podzim jsou dobré houby, dýně a jablka.", "Na podzim se peče bábovka a vaří kulajda."], "zima": ["V zimě se vaří gulášovka, polévky a pečené maso.", "Zima volá po pečeném mase a knedlících."]},
		"why": ["Protože dobrá chuť je v detailech, {voc}."],
		"ask": ["q_food"], "mood": 0.05,
	},
	"visit": {
		"words": ["muzu prijit", "mohu prijit", "mohu navstivit", "navstivim te", "navstivim vas", "pozvete me", "pozvi me", "pozvat me", "zajdu k vam", "zajdu k tobe", "prijdu k vam", "prijdu na navstevu", "na kafe", "na kavu", "na kolac"],
		"lines": ["Jen pojď, až bude čas. Dveře máme otevřené, ale nepřicházej bez telefonu.", "Návštěva vždycky potěší. Jen mi dej vědět dopředu, ať uklidím.", "Přijď v sobotu odpoledne, to bývám doma.",
			"Kafe a koláč se najdou vždycky. Ale nejdřív si zapiš, kde bydlím.", "Samozřejmě, rád{g: tě uvidím|a tě uvidím}. Ale ne moc pozdě.", "Když budeš mít cestu kolem, zaklepej."],
		"trait": {"pratelsky": ["Určitě! Kafe, koláč a dobrá nálada. Pojď kdykoliv.", "Přijď, přijď! Děti budou mít radost."],
			"prisny": ["Návštěva je možná po předchozí domluvě. Zvonek funguje.", "Přijďte v domluvený čas, prosím."],
			"bruclavy": ["Zase někdo chce kafe... no dobře, ale jen chvilku.", "Příště zavolej. Nerad{g:|a} překvapuju."],
			"plachy": ["No... možná jindy. Nerad{g:|a} hostím.", "Dneska ne. Ale třeba někdy."],
			"veselak": ["Jasně! A přines něco k pití, já mám jen čaj!", "Přijď! Dáme pivko a pokecáme!"]},
		"cond": {"friend": ["Ty jsi u nás vždycky vítaný. Přijď klidně dnes večer.", "Pro tebe máme vždycky otevřeno. Jen přines dobrou náladu."], "disliked": ["Na návštěvu ti nepomůžu. Zkus to jinde.", "Radši ne. Nebudeme si dělat naděje."],
			"night": ["V noci na návštěvu? To není vhodné. Přijď zítra.", "Je pozdě, zítra."], "event_vanoce": ["O Vánocích jsme s rodinou. Ale po svátcích se stav."]},
		"season": {"zima": ["V zimě se hodí návštěva: čaj a teplo u kamen.", "V zimě je dobré mít hosta u kamen."]},
		"why": ["Protože návštěva je radost, {voc}, když se ohlásí."],
		"ask": ["q_visit"], "mood": 0.05,
	},
	"complaint": {
		"words": ["stiznost", "stezovat", "stezuju", "stezuji", "nadavam", "me stve", "vadi mi", "otravuje", "nesnasim", "hruza", "nechapu proc", "neni to fer", "ztezuju", "nespravedl", "uz me to nebavi", "je to na nic", "otravny", "otravna", "zase to", "naserte", "hluk"],
		"lines": ["To chápu. Já bych taky nadával{g:|a}.", "Je to k vzteku, ale s tím se nic nenadělá.", "Tak ti to musí být líto. Povídej.", "Dej si vodu a nadechni se. Ráno moudřejší večera.",
			"Každý má svoje starosti. Ty naše se jmenují sousedé.", "Kdyby to bylo jednoduché, nikdo by si nestěžoval. A to je taky pravda."],
		"trait": {"pratelsky": ["Chudáku, pojď si sednout. Řekni, co tě trápí.", "Neboj, všechno se spraví. Jen to chce čas."],
			"bruclavy": ["Tak to jsme dva. Taky mě všechno štve.", "Všechno je špatně, já ti to povím!"],
			"moudry": ["To bývá. Nejhorší je, že to přejde, a pak zase přijde.", "Mladý, nestěžuj si, to je začátek moudrosti."],
			"prisny": ["Stížnost podejte písemně na úřadě.", "Nebudeme se stěžovat. Budeme jednat."],
			"veselak": ["Hlavu vzhůru! Pivo spraví všechno. Skoro všechno.", "Nestěžuj, nebo ti to někdo vezme a dá ti víc!"],
			"plachy": ["Mrzí mě to. Nevím, co říct.", "To je mi líto. Nerad{g:|a} dávám rady."]},
		"cond": {"raining": ["Déšť tu náladu ještě zhoršuje. Zítra bude líp.", "V dešti se všechno zdá horší."], "drunk": ["Ty ses asi trochu napil. Stěžuj si ráno.", "V tomhle stavu každý problém vypadá větší."],
			"recent_offense": ["Za to, co se stalo, si můžeš trochu i ty. Ale pomohu ti.", "Tohle se stalo, protože jsi něco provedl{g:|a}, že?"], "friend": ["Tobě rád{g:|a} naslouchám. Povídej.", "Mezi přáteli se sdílí i to špatné."]},
		"season": {"zima": ["V zimě je všechno horší. Tma, zima a náledí.", "V zimě se stěžuje nejvíc."]},
		"why": ["Protože svět není spravedlivý, {voc}. Ale my můžeme být."],
		"ask": ["q_help"], "mood": 0.04,
	},
	"help_me": {
		"words": ["pomoz mi", "pomozte mi", "potrebuju pomoc", "potrebuji pomoc", "muzes mi pomoct", "muzete mi pomoct", "potrebuju poradit", "poradite mi", "poradis mi", "potrebuju radu", "potrebuji radu", "mam problem", "jsem v tisni", "nevim si rady", "hledam pomoc"],
		"lines": ["Jasně, co potřebuješ? Když budu moct, pomůžu.", "Pomoc je vždycky vítaná. Řekni, o co jde.", "Radu ti dám zdarma. Pomoc už je vzácnější.",
			"S čím konkrétně? Čím víc víme, tím líp poradíme.", "Zkus se zeptat na úřadě, nebo u hostinského, ti pomůžou víc než já.", "Pomoc se najde vždycky. Jen člověk musí chtít."],
		"trait": {"pratelsky": ["Samozřejmě ti pomůžu. Co se děje?", "Neboj, s tím si poradíme."],
			"bruclavy": ["Pomoc? No dobře, ale ať to není na dlouho.", "Zase něco? No, povídej."],
			"moudry": ["Pomoc se nikomu neodpírá. Ale nejdřív uvaž, co potřebuješ.", "Mladý, pojď si sednout, řekneš to postupně."],
			"prisny": ["Pokud jde o zákon, obraťte se na policii. Ostatní řešte s úřadem.", "Pomoc je povinnost. Ale ne do nepořádku."],
			"mlady": ["Jo, klidně. Jen nemám moc peněz.", "No, zkusím to. Co potřebuješ?"]},
		"cond": {"friend": ["Pro tebe všechno. Řekni, co potřebuješ, přítelíčku.", "Ty jsi přítel, tobě se nepomáhá, to se dělá."], "disliked": ["Po tom, co jsi provedl, se ti pomáhá těžko.", "Pomoc? Nejdřív se polepši."],
			"poor": ["Ty jsi na tom bledě s penězi. Zkus vydělat prací ve vsi, někdo vždy něco potřebuje.", "Když nemáš peníze, zkus prodat něco z úrody, nebo si něco přivydělat."],
			"drunk": ["V tomhle stavu ti nejlíp pomůže postel.", "Pomoct? Nejdřív se prospi, pak se ptej."], "night": ["V noci ti moc nepomůžu, všechno je zavřené.", "Zítra ráno to půjde líp."]},
		"season": {},
		"why": ["Protože sousedé si mají pomáhat, {voc}."],
		"ask": ["q_help"], "mood": 0.05,
	},
	"bored": {
		"words": ["nuda", "nudim se", "co delat", "co mam delat", "nevim co delat", "co delas ve volnem", "neco veselyho", "zabavit se", "zabava", "co podniknout", "kam jit"],
		"lines": ["Na vsi se nikdy nenudíš, když máš oči otevřené. Seber houby, zalej zahradu nebo jdi k vodě.", "Nuda je luxus. Dělej něco a čas poletí.", "Zkus rybařit. Nebo si uklidit zahradu, to zabere den.",
			"Běž si sednout na lavičku, třeba se někdo zastaví.", "Když nevíš, co dělat, udělej si kafe a zkus to znovu.", "Zajdi do hospody, tam se vždycky něco děje."],
		"trait": {"mlady": ["Nudím se taky. Dáme spolu nějaký výlet?", "V telefonu je taky pořád nuda."], "veselak": ["Pojď na pivo! To je zábava, co nezklame!", "Nuda? Nuda se léčí pivem a hudbou."],
			"moudry": ["Nuda je dar. Za mladých jsme nestíhali.", "Kdo se nudí, neumí být sám se sebou."], "bruclavy": ["Nudit se můžeš, když máš hotovo. Ale to nikdy nemáš.", "Jdi pomoct sousedovi."]},
		"cond": {"raining": ["V dešti si sedni doma a vař, nebo čti. Nebo jdi do hospody.", "Za deště se dobře spí."], "night": ["V noci je nejlepší spánek. Nebo jdi za světlem hospody.", "V noci nic nepodnikej."],
			"weekend": ["O víkendu je fotbal, nebo v hospodě zábava.", "V sobotu se dá jít na zápas, nebo na pivo."], "winter": ["V zimě je dobrá procházka po sněhu nebo topení v kamnech.", "V zimě se dá sáňkovat, pokud najdeš kopec."],
			"sunny": ["Sluníčko vylákalo ven všechny. Jdi k vodě, nebo do lesa na houby.", "Dneska je ideální počasí na procházku."], "poor": ["Když nemáš co dělat a peníze, přivydělej si u sousedů.", "Zkus brigádu, třeba ti někdo zaplatí."]},
		"season": {"jaro": ["Na jaře se dá sázet, sbírat první kytky a chodit na procházky.", "Jaro je na procházky a práci na zahradě."], "léto": ["V létě se dá jít k vodě, rybařit, nebo jen ležet ve stínu.", "Léto je na koupání a zahrádku."],
			"podzim": ["Na podzim jsou houby a jablka, to je zábava pro celou rodinu.", "Podzim je na houby a pouštění draků."], "zima": ["V zimě se dá topit, číst, sáňkovat a chodit do hospody.", "Zima je na kamna a teplé jídlo."]},
		"why": ["Protože čas se má využít, {voc}, ale i odpočívat."],
		"ask": ["q_walk"],
	},
	"village": {
		"words": ["jak se ti tu zije", "jak se vam tu zije", "jaka je tu ves", "o vsi", "kamen", "zije se tu", "libi se ti tu", "libi se vam tu", "zit na vsi", "na vsi", "vesnice", "ves "],
		"lines": ["Dukelčice jsou malá ves, ale všechno tu je. Hospoda, obchod, hřiště a sousedi.", "Zije se tu dobře, když se nehádáš se sousedy.", "Ves je taková, jací jsou lidé v ní. My jsme docela slušní.",
			"Z města bych se sem nepřestěhoval{g:|a}, ale kdo tu vyrostl, ten tu zůstává.", "V Dukelčicích se nic neděje, což je největší přednost.", "Když tu prší, je to smutné. Když svítí, je to ráj."],
		"trait": {"moudry": ["Za mých mladých let tu žilo víc lidí. Teď se mladí stěhují do města.", "Dukelčice jsou mé srdce. Tady jsem se narodil{g:|a}."], "bruclavy": ["Všechno je tu daleko a nic tu není.", "Ves je fajn, jen silnice jsou samá díra."],
			"pratelsky": ["Máme tu hezké lidi. Kdo chce, najde kamaráda.", "Jsem tu moc spokojená, ves je klidná."], "mlady": ["Je to tu klidné až moc. Občas chybí město.", "Ves je fajn na dětství, ale nevím, jestli na celý život."],
			"drbna": ["Ve vsi je všechno vidět. Nic neutajíš, ani nový plot.", "Tady se nikdo nemůže schovat. Ale taky nikdo nezůstane sám."]},
		"cond": {"stranger": ["Ty jsi tu nový, že? Brzo si zvykneš. Ves je přátelská.", "Vítej v Dukelčicích. Doufám, že se ti tu bude líbit."], "friend": ["Ty už jsi tu doma. Ves tě přijala.", "Brzo z tebe bude skutečný Dukelčák."]},
		"season": {"jaro": ["Na jaře ves rozkvétá a voní trávou.", "Na jaře je ves nejhezčí, v sadech kvetou stromy."], "podzim": ["Na podzim ves voní kouřem z komínů a jablky.", "Na podzim jsou barvy lesa k nezaplacení."], "zima": ["V zimě je ves pod sněhem jak z pohádky.", "V zimě jsou krátké dny a dlouhé večery."]},
		"why": ["Protože tu máme domov, {voc}."],
		"ask": ["q_village"], "mood": 0.05,
	},
	"mushrooms": {
		"words": ["houb", "hrib", "lisk", "muchomurk", "hribovk", "houbar", "kozak", "babka", "prasivk", "kozlak"],
		"lines": ["Houby se sbírají po dešti, ve stínu a hlavně ráno. Kdo má nos, ten najde.", "Hřiby rostou v lese u buků a dubů. Bedlu poznáš podle prstenu.", "Když nevíš, co je to za houbu, nesbírej ji. Jedna chyba stačí.",
			"Houbaření je sport i meditace. Hlavně nezapomeň na nůž a košík.", "Hřiby usušené na zimu jsou poklad do polévky. Kdo to nezkusil, nepochopí.", "V lese jsou houby jen pro toho, kdo se neleká trnek a komárů."],
		"trait": {"moudry": ["Za mých let jsme chodili na houby celá rodina. A všichni se vrátili zdraví, to je ta nejlepší zkouška.", "Hřib nemá v klobouku, jen v chuti."], "bruclavy": ["Houby? Letos nic. A kdyby, stejně by je někdo vysbíral před úsvitem.", "Do lesa s nožem a mlčením."],
			"plachy": ["Houby mám rád{g:|a}. V lese nikdo neruší.", "Houbařím sám{g:|a}, je to klidnější."], "veselak": ["Smažená houba s vajíčkem, to je mňamka! A k tomu pivo.", "Hřib je král lesa. A já jsem král hospody."]},
		"cond": {"raining": ["Po dešti rostou houby jako z vody. Zítra ráno běž do lesa!", "Déšť dnes znamená houby zítra."], "night": ["V noci houby nesbírej, nevidíš, co bereš.", "V noci je les plný zvířat a hub, ale ne pro tebe."],
			"winter": ["V zimě houby nerostou. Aspoň jsou usušené ve spíži.", "V zimě se jen vzpomíná na houby."]},
		"season": {"jaro": ["Na jaře rostou jen smrže a ty se nesbírají.", "Jaro je na kopřivy, ne na houby."], "léto": ["V létě rostou první hřiby a kozáky, hlavně po dešti.", "V létě je ideální čas na lišky a hřiby."],
			"podzim": ["Na podzim jsou houby nejvíc! Hřiby, bedly, klouzky. Nasbírej si na zimu.", "Podzim je houbařská sezona. Vstávej brzo a jdi do lesa."], "zima": ["V zimě houby nejsou. Ale sušené z podzimu jsou na polévku.", "V zimě je tichá půda, pod sněhem houby nerostou."]},
		"why": ["Protože les si říká o pozornost, {voc}."],
		"ask": ["q_mushroom"],
	},
	"health": {
		"words": ["boli", "nemoc", "lekar", "nachlazen", "kasel", "horecka", "zdravi ", "bolest", "zub", "zada", "ordinace", "lek", "leky", "tabletk", "kourim", "cigar", "kaslu", "rym"],
		"lines": ["Zdraví je základ. Až když ti něco je, vidíš, co ti chybí.", "Pij dost vody a spi, je to lék na všechno. Skoro.", "Když tě bolí záda, zkus nevstávat tak prudce. Nebo aspoň nezvedej.",
			"Doktor je v okresním městě, ale do ordinace se jde až když to bolí moc.", "Kdo se hýbe a nekouří, ten žije déle. Aspoň to tvrdí statistika.", "Čaj s medem a teplé ponožky spraví víc než tabletka."],
		"trait": {"prisny": ["V nemocnici vidím, co dělá alkohol za volantem.", "Zdraví se musí hlídat. Preventivní prohlídky nejsou nadávka."], "moudry": ["Nemoc přijde, nemoc odejde. Hlavně nebýt sám.", "Zdraví se nekupuje. Buď ho máš, nebo ne."],
			"bruclavy": ["Všechno mě bolí. Ale to je věkem.", "Doktoři nic neví a leky jsou drahé."], "veselak": ["Smích je nejlepší lék! A pivo je na to tekutý lék, hehe.", "Zdraví? To až ve stáří. Teď žiju!"]},
		"cond": {"drunk": ["Tobě by pomohla voda a spánek, ne víc alkoholu.", "Alkohol zdraví neprospívá, to víš."], "cold": ["V téhle zimě se nachladit je snadné. Obleč se.", "V mrazu nezapomeň na čepici."],
			"raining": ["Po dešti se dávej pozor, nachlazení je za rohem.", "Mokrý člověk je nemocný člověk. Vysušit se."], "hot": ["V horku se pije hodně vody a chodí do stínu.", "Úpal je vážná věc. Měj klobouk."]},
		"season": {"zima": ["V zimě chřipka řádí, tak se hlídej a drž se v teple.", "V zimě se podává čaj s medem a česnek."], "léto": ["V létě pozor na úpal a klíšťata.", "V létě hodně pít a chránit se před sluncem."], "jaro": ["Na jaře bývá únava a alergie.", "Jaro přináší pylovou sezonu."], "podzim": ["Na podzim chřipky a rýmy.", "Na podzim se začíná kašlat."]},
		"why": ["Protože tělo má svou paměť, {voc}."],
		"ask": ["q_help"],
	},
	"tech": {
		"words": ["mobil", "telefon", "internet", "signal", "wifi", "pocitac", "televiz", "tv ", "notebook", "aplikac", "facebook", "tiktok", "hry", "hrat", "konzol", "drone", "dron", "elektrik", "proud"],
		"lines": ["Signál je tu jen u kapličky. To je moderní ves.", "Internet nám občas vypadne, hlavně když jde bouřka.", "Dneska má každý telefon, ale nikdo nevolá.",
			"Technika je dobrá, dokud funguje. Jinak je to jen hromada elektroniky.", "Mladí sedí u mobilu a starší u televize. To je ves dneska.", "Elektrika je základ. Když vypadne proud, ves zná jen svíčky."],
		"trait": {"mlady": ["Signál je tu dneska docela dobrý. U kapličky. Teda, když nefouká.", "Mobil je pro mě všechno. Bez něj bych zemřel{g:|a} nudou."], "bruclavy": ["Všechno je dneska z Číny a za rok to odejde.", "Mobil, internet, samé blbosti."],
			"moudry": ["Za mých let jsme měli telefon jeden na celou ves. A fungoval líp.", "Technika je dobrý sluha, ale špatný pán."], "plachy": ["Internet je můj přítel. Nikdo mě tam neruší.", "Pracuju z domova, takže ano, internet je moje životní čára."]},
		"cond": {"raining": ["V dešti se signál ztrácí. Takže dnes žádný internet.", "V dešti je internet pomalý, ale ještě to jde."], "night": ["V noci je internet nejrychlejší, to je výhoda.", "V noci bývá signál nejlepší."], "windy": ["Vítr nám shazuje dráty, brzy vypadne proud.", "Při větru vypadává elektřina."]},
		"season": {"zima": ["V zimě je internet jediná zábava.", "V zimě se dívá na televizi víc než kdy jindy."]},
		"why": ["Protože technika není dokonalá, {voc}."],
		"ask": ["q_tech"],
	},
	"music": {
		"words": ["hudb", "radio", "kapela", "pisnick", "tancovack", "zpiv", "harmonik", "kytar", "hrajes na", "kdo hraje", "hraje v", "koncert", "plesy", "diskotek", "tanec", "tancovat", "poslech"],
		"lines": ["Rádio doma poslouchám ráno. Má dobrý výběr a občas i něco českého.", "Hudba je dobrá na všechno. Hlavně na smutek.", "Když hraje kapela, nikdo nesedí. Ani ti, co neumějí tančit.",
			"Na tancovačku se chodilo v neděli. Dneska se chodí na diskotéku v okresním městě.", "Písnička do práce a písnička z práce. Tak se žije.", "Když zpívám, sousedi zavírají okna. A já zpívám dál."],
		"trait": {"moudry": ["Dřív se tady tancovalo na návsi každou neděli.", "Harmonika byla dříve v každé chalupě. Dneska je to jen elektronika."], "veselak": ["Pivo a hudba, to je recept na život! Kdo zpívá, ten neplakal.", "Zpívám vždycky. Jen ne vždycky správně."],
			"mlady": ["Hudbu poslouchám v telefonu, celý den. Sluchátka jsou moje další uši.", "Na tancovačku nechodím, radši poslouchám doma."], "prisny": ["Hudba je dobrá do desíti. Potom je klid.", "Noční hluk se nesmí. To je vyhláška."]},
		"cond": {"event_hody": ["Na hodech hraje kapela a všichni tancují. To nesmíš zmeškat.", "O hodech je tancovačka do rána."], "weekend": ["V sobotu večer se někdy hraje v hospodě.", "O víkendu se zpívá."],
			"night": ["V noci je hudba potichu, sousedi spí.", "V noci už se nezpívá."], "event_silvestr": ["Na Silvestra se hraje do rána a rachejtle lítají."]},
		"season": {"zima": ["V zimě je hudba u kamen s rádiem.", "V zimě v hospodě zpívají koledy."], "léto": ["V létě hraje hudba z každého okna.", "V létě bývají venkovní zábavy."]},
		"why": ["Protože hudba spojuje lidi, {voc}."],
		"ask": ["q_music"],
	},
	"event": {
		"words": ["vanoc", "velikonoc", "hody", "masopust", "carodejnic", "silvestr", "svatek", "posviceni", "pomlazk", "stedry den", "adventni", "cukrovi", "kaprem", "rachejtl", "ohnostroj", "dyni", "dusicky"],
		"lines": ["Svátky jsou na vsi nejhezčí. Všichni se sejdou a nikdo nespěchá.", "Každý svátek má svoje: jídlo, tradici a výmluvu nepracovat.", "Tradice držíme. Hlavně ty, u kterých se jí a pije.",
			"Bez tradic by ves byla jen hromada domů.", "Svátky jsou jako poklady, vybíráme je z roku.", "Na vsi se svátky slaví pomalu a pořádně."],
		"trait": {"moudry": ["Za mých let se svátky slavily skromněji, ale srdečněji.", "Tradice jsou to, co nás drží pohromadě."], "veselak": ["Svátky jsou nejlepší! Pivo, hudba a všichni jsou doma!", "Na hodech tančím, i když to neumím."],
			"bruclavy": ["Svátky jsou samá práce a potom nikdo nepoděkuje.", "Dřív byly svátky lepší. Dneska jsou jen komerce."], "prisny": ["Na svátky se má dodržovat klid. Ne křik a rachejtle.", "Zákon o klidu platí i o svátcích."]},
		"cond": {"event_vanoce": ["Vánoce jsou tady! Cukroví, kapr a stromeček. To je radost.", "O Vánocích je ves nejkrásnější. Ozdoby svítí a všichni jsou doma."], "event_masopust": ["Masopust! Dneska se chodí průvodem a koná se zabijačka.", "Na masopust se jí a pije. A masky jsou krásné."],
			"event_carodejnice": ["Dneska se pálí čarodějnice. Pozor na oheň a na děti.", "Čarodějnice dnes v noci! Kdo chce, může přijít k ohni."], "event_hody": ["Hody jsou tady! Tancuje se celou noc. Přijď na stavění máje.", "Na hodech je ves vzhůru, a spí se až v pondělí."],
			"event_silvestr": ["Silvestr, to je velká slavnost. Ohňostroj, šumivé víno a dobré předsevzetí.", "Na Silvestra se v hospodě slaví až do rána."], "holiday": ["Dneska je svátek, tak všechno zavřeno. Jen hospoda drží."]},
		"season": {"jaro": ["Na jaře jsou Velikonoce a čarodějnice. Pomlázka a oheň.", "Jaro je začátek svátků a zahrádkáření."], "léto": ["V létě jsou hody a svatby. Kdo chce, může tancovat.", "V létě jsou hody, to je velká událost."], "podzim": ["Na podzim jsou dušičky a posvícení. Jíme husy a koláče.", "Podzim je poklidný, ale posvícení je radost."], "zima": ["V zimě jsou Vánoce a masopust. A taky Silvestr.", "V zimě je svátek za svátkem."]},
		"why": ["Protože tradice drží ves pohromadě, {voc}."],
		"ask": ["q_event"], "mood": 0.05,
	},
	"ghost": {
		"words": ["strasi", "strasid", "duch", "tma ", "temnota", "bat se", "bojim se", "pohadk", "legend", "povesti", "bila pani", "zjeveni", "kaplick"],
		"lines": ["U kapličky prý straší Bílá paní. Ale spíš je to mlha.", "Ve vsi se vypráví o černém psovi na silnici. Kdo ho viděl, ten už pivo nepil.", "V noci v lese není nic hrozného. Jen tma a divoká zvěř.",
			"Děti se bojí tmy, dospělí se bojí účtů. Každému to svoje.", "Za kostelem prý chodí starý farář. Nikdo ho neviděl, ale všichni o něm mluví.", "Kdo věří na duchy, ten je vidí. Kdo nevěří, ten si to nechává pro sebe."],
		"trait": {"moudry": ["Za mých mladých let se vyprávělo o světýlkách v lese. Byla to bludička, nebo jen pálenka?", "Povídaček je na vsi dost. A v každé je kousek pravdy."], "plachy": ["Nerad{g:|a} chodím v noci sám{g:|a}. Tmy se nebojím, jen lidí.", "O duchách mluvit nechci."],
			"veselak": ["Ducha jsem nikdy neviděl, ale jednou jsem viděl, jak se hýbou lavičky. Možná jsem byl jen trochu unavený.", "Duchové? Ti pijí pivo s námi, jen je nikdo nevidí!"], "mlady": ["Straší to tu jen když vypadne internet.", "Jednou jsme se bavili o duchu a zhasly se světla. Fakt!"]},
		"cond": {"night": ["Jsi venku v noci? Tak poslouchej, jestli neslyšíš kroky.", "V noci se po vsi nechodí bez baterky. Nikdy nevíš."], "fog": ["V mlze se zjevují věci, co tam nejsou. Nebo jsou.", "V mlze je ves zvláštní. Tichá."],
			"event_carodejnice": ["Dnes v noci létají čarodějnice. Zamkni okno!"], "winter": ["V zimě se vyprávějí nejlepší příběhy, u kamen a se svíčkou.", "Zima je na strašidelné povídky."]},
		"season": {"podzim": ["Na podzim se vyprávějí nejlepší strašidelné příběhy. Dušičky jsou blízko.", "Podzim je sezona duchů a mlhy."]},
		"why": ["Protože lidé rádi věří v záhady, {voc}."],
		"ask": ["q_ghost"],
	},
	"earn": {
		"words": ["vydelat", "brigad", "kde se da sehnat praci", "sehnat praci", "hledam praci", "potrebuju penize", "jak zbohatnout", "chci penize", "chci vydelat", "najit praci", "prace pro me", "nejaky vydelek", "prodat"],
		"lines": ["Vydělat se dá prací ve vsi: někdo vždycky něco potřebuje.", "Brigáda v sadu, sklizeň, pomoc sousedovi. Peníze nechodí samy.", "Kdo umí pracovat, ten ve vsi hladem nezemře.",
			"Zkus prodat, co nepotřebuješ. V Potravinách vykupují zeleninu, vejce i maso.", "Pomáhat se vyplatí. Nejen penězi, ale i pověstí.", "Žádná práce není ostuda. Jen nezaměstnání je ostuda."],
		"trait": {"mlady": ["Brigáda v sadu, trhám jablka. Nic moc, ale na řidičák to stačí.", "Když nemáš peníze, musíš makat. Nebo prodávat věci na internetu."], "bruclavy": ["Peníze se vydělávají těžce a rozfofrují rychle.", "Dřív se vydělávalo víc, teď všechno zdražilo."],
			"moudry": ["Kdo nemá peníze, ať ušetří. Kdo je má, ať neutrácí.", "Poctivá práce, poctivé peníze. Tak to bylo a tak to je."], "prisny": ["Poctivá práce, poctivá výplata. Žádné černé kšefty.", "Vyhněte se nelegální práci, má to pak následky."]},
		"cond": {"poor": ["Vidím, že nemáš moc v kapse. Zkus úkoly, co nabízí ves. Zmáčkni E u hospodského nebo u úřadu.", "Nemáš moc peněz? Zajdi za starostou, nebo za hospodským, třeba mají práci."], "rich": ["Ty už jsi dost zámožný. Možná bys mohl zaměstnat jiné.", "S penězi se má zacházet s rozumem. Nejlíp investovat do pole."],
			"carry_fish": ["Tu rybu prodej, nebo si ji upeč. Je to slušný výdělek.", "Ryby se prodávají. Někdy i dobře."], "carry_game": ["Zvěřina se prodává jen s dokladem o původu. Jinak máš problém."], "carry_veg": ["Zeleninu prodej v Potravinách, vykupují ji.", "Zelenina z vlastní zahrady, to je výdělek."]},
		"season": {"podzim": ["Na podzim je práce v sadech a na polích, to jsou slušné peníze.", "Podzim je na brigády nejlepší."], "léto": ["V létě je sezonní práce na poli a v zahradách.", "V létě je dost práce, jen se chtít."]},
		"why": ["Protože nikdo nic nedá zadarmo, {voc}."],
		"ask": ["q_help"],
	},
	"philosophy": {
		"words": ["smysl zivota", "stesti", "co je dulezite", "jaky je zivot", "zivot je", "proc zijeme", "co mas rad", "co te bavi", "co te tesi", "co te stve", "spokojen", "sny ", "sen ", "budoucnost"],
		"lines": ["Štěstí je sedět večer na lavičce a nemuset nic.", "Život je jako pole: co zaseješ, to sklidíš. A někdy i to, co nezaseješ, třeba plevel.", "Nejdůležitější je zdraví, rodina a dobré sousedství. A potom pivo.",
			"Být spokojený s málem, to je největší umění.", "Budoucnost? Ta přijde. Hlavní je, co uděláš dneska.", "Nejhezčí věci jsou zadarmo: slunce, vítr a dobré slovo."],
		"trait": {"moudry": ["Čím jsem starší, tím míň toho vím. A tím víc se mi to líbí.", "Hlavní je nebýt sám a mít co dělat."], "veselak": ["Smysl života? Pivo a dobří přátelé. Co víc?", "Život je krátký, tak ať je veselý!"],
			"bruclavy": ["Smysl života? Práce a zase práce, pak důchod a bolavá záda.", "Všechno je marnost. Ale pivo je dobré."], "mlady": ["Já nevím. Zkouším to zjistit. Zatím spím a dělám, co mě baví.", "Budoucnost? Nejdřív řidičák, pak uvidíme."],
			"prisny": ["Smysl života je plnit povinnosti a dodržovat řád.", "Nejdůležitější je spořádanost."]},
		"cond": {"night": ["V noci o tom člověk přemýšlí víc. Bývá pak těžké usnout.", "V noci se dobře přemýšlí o životě."], "raining": ["V dešti se dobře filozofuje.", "Déšť k filozofii sedí."], "friend": ["Tobě to řeknu upřímně: dělej, co tě baví, a nenech se zahnat.", "Ty jsi dobrý člověk. Drž se toho."]},
		"season": {"zima": ["V zimě člověk přemýšlí víc, je na to čas.", "Zimní večery jsou na filozofii."], "jaro": ["Na jaře člověk věří, že všechno bude lepší.", "Jaro dává naději."]},
		"why": ["Protože to tak je, {voc}. Nebo aspoň já si to myslím."],
		"ask": ["q_philo"], "mood": 0.05,
	},
	"bus": {
		"words": ["autobus", "zastavk", "jizdni rad", "vlak", "nadrazi", "spoj ", "spoje", "dojizd", "do mesta", "do okresniho", "busem"],
		"lines": ["Autobus jezdí párkrát denně. Kdo ho nestihne, jde pěšky nebo čeká.", "Do okresního města se jezdí busem, nebo autem. Na kole je to fuška.", "Zastávka je u hlavní silnice. Jízdní řád je na ní, jen ho nikdo nečte.",
			"Busy nejezdí v neděli a o svátcích, takže buď auto, nebo trpělivost.", "Když vlak vynechá, je to zpoždění. Když bus vynechá, je to tradice.", "Dojíždět do práce busem je dobrodružství. Hlavně ráno."],
		"trait": {"bruclavy": ["Ty silnice jsou samá díra, to vám povím. A autobus se na nich drncá jak na ohradě.", "Jízdní řád se mění podle nálady dopravce."], "mlady": ["Dojíždím do školy busem. Je to nuda, ale aspoň mám čas na mobil.", "Bus? Nic moc. Nejradši bych měl vlastní auto."],
			"moudry": ["Za mých let jsme chodili pěšky a nikdo si nestěžoval.", "Autobus je pokrok, ale moc nepomáhá."]},
		"cond": {"night": ["V noci nic nejede, takže buď auto, nebo chůze.", "Noční spoj tu nikdy nebyl."], "weekend": ["O víkendu nejede skoro nic.", "V neděli žádný autobus."], "winter": ["V zimě bus někdy nejede kvůli sněhu.", "Zimní busy mívají zpoždění."]},
		"season": {"zima": ["V zimě se bus zasekne ve sněhu. Nebo nejede vůbec.", "V zimě jsou silnice zasněžené."]},
		"why": ["Protože je to malá ves, {voc}. Kdo jede, ten má štěstí."],
		"ask": ["q_car"],
	},
	# ---------------------------------------------------------------- témata s původními záměry (rozšíření)
	"goodbye": {
		"lines": ["Tak se měj!", "Na shledanou, {voc}!", "Dávej na sebe pozor.", "Přijď zase, ať máme o čem mluvit.", "Tak zatím, ať se daří.", "Pa, pozdravuj doma.", "Měj se hezky, {voc}."],
		"trait": {"prisny": ["Na shledanou.", "Dobrý den a pěkný zbytek dne."], "bruclavy": ["Zdar.", "Tak jo, jdi."], "mlady": ["Čau!", "Měj se, kámo!", "Mějte se!"], "moudry": ["S pánembohem, {voc}.", "Opatruj se."], "veselak": ["Čau, a na zdraví!", "Tak zatím a pivo za mnou!"],
			"plachy": ["…Na shledanou.", "Tak pa."], "drbna": ["Tak zatím, a nezapomeň vyprávět, co se děje!", "Ahoj, a ať slyšíme novinky!"], "pratelsky": ["Měj se krásně, {voc}!", "Těšilo mě, přijď zas."]},
		"cond": {"night": ["Dobrou noc, {voc}. Ať se ti dobře spí.", "V noci opatrně, ať nezabloudíš."], "morning": ["Hezký den!", "Ať se dnešek povede."], "evening": ["Hezký večer!", "Dobrou noc a sladké sny."], "raining": ["Tak se nezmoč, {voc}.", "Vem si deštník, ať nezmokneš."],
			"snowing": ["Dávej pozor na ledu, ať nespadneš.", "Teplo se oblékni, ať nenastydneš."], "drunk": ["A jdi rovnou domů, ať neskončíš v příkopě!", "Domů a spát!"], "friend": ["Tak se měj, kamaráde! Dveře mám pro tebe vždycky otevřené.", "Přijď brzy, ať se nezapomeneme."],
			"event_vanoce": ["Krásné Vánoce, {voc}!", "Hezké svátky!"], "event_silvestr": ["Šťastný nový rok, {voc}!", "Ať se v novém roce daří!"], "weekend": ["Hezký víkend!", "Užij si volno."]},
		"season": {"zima": ["Ať tě zima nechytí, {voc}.", "V tepličku a s čajem, tak se měj."], "léto": ["Ať tě sluníčko nespálí!", "Užij si léto, {voc}."]},
		"social": true,
	},
	"thanks": {
		"lines": ["Není zač!", "Rádo se stalo.", "Nemáš zač, {voc}.", "To je maličkost.", "Jsem rád{g:|a}, že jsem pomohl{g:|a}.", "Od toho jsou sousedé."],
		"trait": {"prisny": ["To je samozřejmost.", "Děkuji, že oceňujete."], "bruclavy": ["No jo, no jo. Nemáš zač.", "Hm, není zač."], "veselak": ["Jednou pivem se to spraví!", "Nemáš zač, příště to zaplatíš!"], "plachy": ["…Rádo se stalo.", "(kývne)"],
			"moudry": ["Není zač, {voc}. Dobrota se neztrácí.", "Tak to je dobře."], "mlady": ["Nic to nebylo!", "Jo, v pohodě!"], "drbna": ["Nemáš zač, zlatíčko! A nezapomeň, že to byla ode mě.", "Rádo se stalo, už to vědí všichni!"]},
		"cond": {"recent_quest": ["Děkuju taky! Díky tobě se ve vsi dělá dobře.", "To já bych měl{g:|a} děkovat. Pomohl jsi nám."], "friend": ["Pro tebe všechno, kamaráde.", "Přátelé si nedějí díky, přátelé si pomáhají."], "recent_gift": ["A já děkuju za ten dárek, pořád si ho vážím.", "Dárek byl skvělý, díky taky."]},
		"season": {},
		"social": true,
	},
	"compliment": {
		"lines": ["Děkuju, to potěší!", "Ty jsi ale hodný člověk!", "To je hezké, díky!", "No to se mi líbí slyšet.", "Díky, občas to potřebuju slyšet.", "Zahřálo to u srdce."],
		"trait": {"prisny": ["Děkuji.", "To je od vás hezké."], "bruclavy": ["No… díky.", "Hm. To jsem nečekal{g:|a}."], "plachy": ["(usměje se) Děkuju.", "Díky."], "drbna": ["Ty jsi ale zlatíčko!", "To řeknu všem, jak jsi milý!"],
			"veselak": ["Hehe, ještě jednou a dám ti pivo!", "To jsem rád{g:|a}! Budu to opakovat celé hospodě."], "moudry": ["Díky, {voc}, to hřeje.", "Lichotka stará, ale vždy ráda přijatá."], "mlady": ["Jé, díky!", "No to je milé!"]},
		"cond": {"friend": ["Tobě věřím, to je od srdce.", "Od přítele je to dvojnásobně hezké."], "outfit_slavnostni": ["Ty se taky pěkně oblékáš.", "Sako ti sluší, nemyslíš?"], "recent_harvest": ["Díky! Ty jsi zase dobrá zahradnice?"], "raining": ["Aspoň něco dobrého v tom dešti.", "Takový kompliment potřebuju víc než deštník."]},
		"season": {},
		"social": true,
	},
	"howareyou": {
		"lines": ["Dobře, díky! A ty?", "Jde to, pořád se něco děje.", "Docela dobře, na to, jaká je doba.", "Mám se, nestěžuji si. A co ty?", "Jako vždycky – práce, starosti, ale pořád jedu.", "Když se ráno probudím, už to je dobrý den."],
		"trait": {"pratelsky": ["Moc dobře, děkuju za optání!", "Skvěle, že ses zeptal!"], "drbna": ["Dobře, ale ta Hromádková, to ti povím…", "Ale jo, jen těch novinek je tolik!"], "bruclavy": ["Ale, jak by se mělo. Záda bolí, důchod malej…", "Blbě. Jako vždycky."],
			"prisny": ["Děkuji, dobře.", "Nestěžuji si."], "veselak": ["Bezva, jen žízeň mám!", "Líp než včera, hůř než zítra!"], "plachy": ["Dobře.", "Ujde to."], "moudry": ["Na můj věk dobře, {voc}. Hlavně že nohy slouží.", "Pánbůh zaplať, dobře."], "mlady": ["V pohodě.", "Dobrý, jen se nudím."]},
		"cond": {"raining": ["Dneska mě bolí klouby, ale jinak fajn.", "V dešti bývám {g:líný|líná}, ale dám to."], "hot": ["Ve vedru se nedá ani dýchat. Ale dobré.", "Horko mě ubíjí, ale zvládám to."], "cold": ["Zima mi leze do kostí. Jinak dobré.", "Je kosa, ale držím se."], "night": ["V noci nespím, tak jsem trochu unavený.", "Už je pozdě, takže jsem rád{g:|a}, že jsem vzhůru."],
			"morning": ["Ráno jsem trochu {g:rozespalý|rozespalá}, ale zvládnu to.", "Dobré ráno! A už mám kafe."], "weekend": ["Je víkend, takže dobře!", "O víkendu se mám vždycky líp."], "event_vanoce": ["O Vánocích se mám dobře, jen mi roste pas.", "Vánoční nálada, takže skvěle!"], "friend": ["Tobě to řeknu upřímně: dneska je to těžké, ale díky, že se ptáš.", "S tebou se mi mluví dobře, takže dobře!"],
			"recent_fish": ["Dobře! A ty jsi prý chytil rybu, slyšel{g:|a} jsem."], "recent_harvest": ["Dobře, slyšel{g:|a} jsem, že se ti daří na zahradě."]},
		"season": {"jaro": ["Na jaře je mi vždycky lépe, slunce zahřeje.", "Jaro mi dodává síly."], "zima": ["V zimě bych nejraději hibernoval{g:|a}.", "V zimě se držím, ale nejradši u kamen."]},
		"social": true,
	},
	"money": {
		"lines": ["Nemám nazbyt. Ale na silnicích se prý válejí dukáty!", "Zkus pomoct lidem ve vsi, někdo ti za to i zaplatí.", "Peníze jsou vzácnost. Ale pár korun by se našlo, kdyby šlo o něco důležitého.",
			"S penězi je to těžké. Buď je nemáš, nebo je máš a bojíš se je utratit.", "Kdo chce peníze, ať si je vydělá. Nikdo ti je nedá zadarmo.", "Půjčit, to je o přátelství. A já tě ještě dobře neznám."],
		"trait": {"bruclavy": ["Peníze? Ty si vydělej!", "Nepůjčuju. Zásadně."], "prisny": ["Nepůjčuju peníze. Je to zásada.", "Peníze se vydělávají prací, ne půjčkou."], "veselak": ["Peníze? Dneska jsem zaplatil pivo, takže nic nemám!", "Příště, až budu mít. Teď je kapsa prázdná."],
			"moudry": ["Kdo si půjčuje, ten se zadlužuje. Radši si vydělej.", "Peníze jsou sluha, ne pán."], "mlady": ["Sám nemám, kámo. Šetřím na řidičák.", "Jo, kdybych měl, půjčím. Ale nemám."], "plachy": ["Nemám. Promiň.", "Nerad{g:|a} půjčuju."], "drbna": ["Peníze nemám, ale vím o tom, kdo má, ale nevím, jestli ti půjčí.", "Půjčit? No, ptej se sousedky, ta má."]},
		"cond": {"friend": ["Tobě bych pomohl{g:|a}, ale dnes nemám u sebe nic. Přijď zítra.", "Přítel se v nouzi pozná. Teď ale sám nemám, počkej trochu."], "disliked": ["Po tom všem, co o tobě slyším? Ne.", "Ty si chceš půjčovat? Nejdřív se polepši."], "poor": ["Ty jsi na tom špatně, co? Zkus vydělat úkoly ve vsi.", "Brigáda, to je cesta. Zajdi do hospody, nebo na úřad."], "drunk": ["V tomhle stavu ti nepůjčím ani korunu.", "Nejdřív vystřízlivěj."]},
		"season": {},
		"mood": 0.0,
	},
	"food": {
		"lines": ["V Potravinách mají rohlíky a tlačenku. V hospodě uvaří guláš.", "Hlad? V hospodě mají smažák jak podrážku, ale dobrej.", "Když máš hlad, v kapse se vždy najde kus chleba. Nebo tě pozvu na oběd.", "Kdo má hlad, ten se nají. Jen musí vědět kam.",
			"Nejlepší jídlo je to, co uvaříš sám. Ale zadarmo nic nebude.", "V obchodě jsou rohlíky od šesti, v hospodě guláš a u sousedky koláče."],
		"trait": {"pratelsky": ["Pojď na koláč, mám čerstvé. Nebo si něco uvař z toho, co máš.", "Hlad? Přijď ke mně, něco se najde."], "veselak": ["Guláš a pivo, to je základ! A smažák jako přílohu!", "Jídlo je v hospodě. Pivo taky!"], "bruclavy": ["Jídlo se kupuje. Nebo vaří. Nikdo ti nedá zadarmo.", "Jít do obchodu, to je jednoduché."],
			"moudry": ["Kdo nemá co jíst, ať se podívá na zahradu. Tam vždycky něco roste.", "Chleba se sádlem, to je základ, {voc}."]},
		"cond": {"drunk": ["Něco sněz, pomůže ti to vystřízlivět.", "Rohlík nebo chleba se sádlem ti srovná žaludek."], "carry_veg": ["Zeleninu už máš, tak si uvař polévku.", "Zelenina z vlastní zahrady, tak to je jídlo!"], "carry_fish": ["Rybu máš, upeč si ji na ohni. Nebo uvař polévku.", "S rybou se najíš a je to zdravé."],
			"carry_game": ["Zvěřinu upeč, až bude vyvržená. Dobrá věc.", "Zvěřina je výborná, ale musí se správně připravit."], "morning": ["Ráno nejlepší snídaně je rohlík a čerstvé mléko.", "Od šesti jsou v obchodě rohlíky."], "night": ["V noci bude zavřeno všude, jen v hospodě ti snad něco dají.", "Noční hlad se řeší chlebem se sádlem."],
			"winter": ["V zimě jsou nejlepší polévky a guláš.", "V zimě se jí víc, to je normální."]},
		"season": {"podzim": ["Na podzim jsou jablka, hrušky a houby. Jez a nadechuj se.", "Podzim je sklizeň jídla, takže se nají každý."], "léto": ["V létě jsou rajčata, okurky a ovoce, to je zdravé.", "V létě se jí lehce."], "zima": ["V zimě se jí těžší jídlo: guláš, svíčková.", "V zimě se topí, a proto se i víc jí."], "jaro": ["Na jaře je málo zásob, ale zelenina začíná růst.", "Na jaře se jí první zelenina."]},
		"ask": ["q_food"],
	},
}

## Navazující reakce, když téma nemá vlastní pole (klíč = `why` / `more` / `how` / `where` / `andyou`), dle povahy.
const FOLLOW_FALLBACK := {
	"why": {"_": ["Tak to prostě je.", "Nevím, tak se to říká.", "Dobrá otázka, ale nemám na ni odpověď."], "bruclavy": ["Protože jo. A basta.", "Co já vím, zeptej se někoho jiného."], "prisny": ["Protože tak to stanoví pravidla.", "To je dáno zvyklostí."],
		"moudry": ["Protože život je složitý, {voc}.", "To ti povím, až budeš starší."], "veselak": ["Protože pivo je dobré! Nebo protože ne.", "Proč? No protože!"], "mlady": ["No… prostě. Nevím.", "Jako fakt netuším."], "plachy": ["Nevím…", "To nevím."], "drbna": ["To ti neřeknu, ale povídá se… nevím.", "Proč? Ale to víš, každý si myslí něco jiného."]},
	"more": {"_": ["Víc už k tomu nevím.", "To je asi všechno, co k tomu umím říct.", "Co ti mám ještě říct?"], "bruclavy": ["Už jsem řekl dost.", "Víc z toho nevyždímáš."], "moudry": ["Kdo chce vědět víc, ať se zeptá někoho jiného.", "Víc už nevím, {voc}."], "veselak": ["To je všechno! Ale pivo je pořád dobré.", "Víc? Už jsem vyčerpal{g:|a} zásoby, hehe."]},
	"how": {"_": ["Zkus to a uvidíš.", "To musíš zkusit sám, {voc}. Rady jsou drahé.", "Nejlepší je dělat a učit se z chyb."], "prisny": ["Dodržuj pravidla a nic se ti nestane.", "Nejdřív si zjisti předpisy."], "bruclavy": ["Jak na to? Musíš makat.", "Nikdo ti to neřekne, musíš na to přijít sám."], "moudry": ["Pomalu a s rozmyslem.", "Učit se z toho, co dělají jiní."]},
	"where": {"_": ["Kousek odsud. Zeptej se někoho.", "To ti nepovím přesně, zkus se porozhlédnout.", "Kde? No, všude kolem."], "bruclavy": ["Všude a nikde. Hledej.", "Zeptej se jinde."], "prisny": ["Na správném místě.", "Zjisti si to na úřadě."]},
	"andyou": {"_": ["Já? Tak nějak, jako vždycky.", "Já jsem v pořádku, díky.", "Mně se daří, nestěžuji si."], "bruclavy": ["Já se neptám, ty neptej.", "Co s tím?"], "veselak": ["Já? Skvěle, jen bych si dal pivo!", "Já jsem vždycky v pohodě!"], "drbna": ["Já? To ti povím, ale až jindy.", "Mně? Ale povídej ty!"], "plachy": ["Já…dobře.", "No… docela dobře."]},
}

## Stručné vysvětlení, když postava odmítá opakovat téma (paměť rozhovoru – odpovědi jsou vyčerpané).
const EXHAUSTED := {
	"_": ["Tohle už jsem ti celé řekl{g:|a}. Víc nevím.", "Už jsme o tom mluvili, {voc}. Nic dalšího mě nenapadá.", "To jsem ti říkal{g:|a}. Zeptej se na něco jiného."],
	"bruclavy": ["Už jsem to říkal! Jsi hluchý?", "Stejná otázka, stejná odpověď. Nic nového."], "veselak": ["Hele, už se opakujeme! Dáme si něco jiného?", "To už bylo. Zkus jiné téma, nebo jiné pivo."], "prisny": ["K tomu jsem již vše uvedl{g:|a}.", "Opakování mi nic nepřidá."],
	"moudry": ["Vždyť jsem ti to už vyprávěl{g:|a}, {voc}.", "Paměť mám dobrou. A už jsem to říkal{g:|a}."], "mlady": ["Hele, už jsem to říkal{g:|a}, nemám nic nového.", "To jsem ti říkal{g:|a}, fakt."], "plachy": ["Už jsem to říkal{g:|a}…", "Víc nemám."], "drbna": ["To jsi už slyšel{g:|a}! Zeptej se na něco nového, ať máme o čem mluvit.", "Už jsem ti řekl{g:|a} všechno. Teda skoro."],
}

## Předpona, když téma patří k oblíbeným tématům postavy (`Characters.PROFILES[*].topics`) – postava je nadšená.
const EXPERT_PREFIX := {
	"_": ["Tohle je moje téma! ", "No to jsi se trefil{g:|a}! ", "To je přesně něco pro mě. "], "bruclavy": ["Když už se ptáš… ", "Tak na tohle se nikdo neptá, ale dobře. "], "prisny": ["K tomu se dá říct hodně. ", "Toto je důležité téma. "],
	"veselak": ["Hehe, to je řeč! ", "Jo! Na tohle jsem si počkal{g:|a}! "], "moudry": ["No vidíš, {voc}, o tom bych mohl{g:|a} vyprávět. ", "To je dlouhá kapitola. "], "mlady": ["Jo, tohle mě baví! ", "Hustý téma! "], "plachy": ["…To je moje téma. ", "Tohle mám rád{g:|a}. "], "drbna": ["To je můj obor! ", "No to mi povídej! "],
}

## Odkaz na odborníka (postava téma nezná, ale ví, kdo ano): {expert}, {expert_job}.
const REFERRALS := ["Tomu moc nerozumím. Na tohle je odborník {expert}, {expert_job}.", "Na tohle se zeptej, až potkáš – {expert}, {expert_job}. Poradí líp než já.",
	"Hm, to není můj obor. {expert} ({expert_job}) o tom ví víc.", "Tohle ti líp vysvětlí {expert}, {expert_job}."]
